### ISSUE TITLE
Identifier les opportunités de financement pertinentes

### ISSUE THREAD

**Issue by emchateau** [museonum/seminaire#2]

**Comment by PRoy-Michaud** [comment]
Voici les trois bourses qu'on m'a proposé lorsque j'ai discuté avec Philippe Lebel (FAECUM):

- Mois de la recherche étudiante (date limite = 15 janvier 2017) : Première condition, que l'activité se déroule durant le mois de mars. Ils privilégient les activités qui laissent la parole aux étudiants. Ce qui est exactement notre intention avec le séminaire étudiant. Rapidement nous répondons aux critères d'admissibilité si je ou l'AEMMUM fait la demande. https://www.ficsum.com/wp-content/uploads/2013/05/R%C3%A8glements_MRE20162017.pdf

- PIÉ (date limite = 25 janvier) : Les dépenses couvertes sont les suivantes,
Frais de location de salle à l’UdeM ou dans un environnement justifié ;
Frais de location de matériel ;
Frais de transport de matériel ;
Frais de nourriture et boissons (à l’exception de l’eau embouteillée) ;
Frais d’honoraires professionnels (maximum de 250 $ par projet) ;
Frais de conférencières ou de conférenciers (maximum de 250 $ par projet). 
Selon les critères, nous pouvons appliquer 
http://www.faecum.qc.ca/ressources/bourses/descriptif-projets-d-initiative-etudiante-pie

- SIÉ : date limite 1er décembre. Nous ne pouvons y appliquer pour cette année. Doit être faite par l'association étudiante.

**Comment by emchateau** [comment]
Merci beaucoup pour ces précisions.
Le plus urgent paraît donc de se diriger vers le financement pour le mois de la recherche étudiante.
Je me renseigne de mon côté sur le financement possible pour l’organisation d’un cycle de séminaire ou de conférences.
