### ISSUE TITLE
Organiser une télé-réunion

### ISSUE THREAD

**Issue by emchateau** [museonum/seminaire#3]
Bonjour @PRoy-Michaud, seriez-vous libre dans les prochains jours pour une télé-réunion afin de travailler sur le dossier de financement ?
Bien cordialement,
Emmanuel

**Comment by PRoy-Michaud** [comment]
Bonjour Monsieur Château,

Je serai disponible du 30 au 1er. Par la suite, je serai en simulation parlementaire jusqu'au 6 janvier. 

Cordialement
Patricia

**Comment by emchateau** [comment]
Chère Patricia, 
Pouvons-nous fixer quelque chose le 7 janvier. Par exemple, samedi à 11h ?
Cordialement,
Emmanuel

**Comment by PRoy-Michaud** [comment]
Bonjour M Château,

Veuillez me pardonner du délais. Les deux derniers jours ne m'ont pas permise d'aller sur mon courriel. 

Je serais disponible dès 11h30 le 7 janvier.

**Comment by emchateau** [comment]
Chère Patricia,
Sans nouvelle de votre part, j’avais prévu autre chose ce matin. Toutes mes excuses. Nous pouvons reporter à demain ou lundi, comme vous préférez ?
Bien cordialement,
Emmanuel

**Comment by PRoy-Michaud** [comment]
Bonjour M Château,

quitte à attendre à lundi, je serai sur Montréal dès Mardi pour la reprise des cours. Nous pouvons toujours prendre rendez-vous ce Mardi en après-midi. Sinon, lundi matin serait un meilleur moment pour moi.
Cordialement,
Patricia
